(function(){'use strict';
const root=document.getElementById('manager'),D=window.PUBLIC_320;
if(!root)return;
if(!D?.graphSnapshot||!D?.decision){root.textContent='公開用データを読み込めませんでした。再読み込みしてください。';return;}
const E=v=>String(v??'未確認').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const d=D.decision,g=D.graphSnapshot,R=D.running;
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
const saved=new Date(g.savedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',hour12:false})+' JST';
root.innerHTML=`<div id="managerApp"><section id="autonomyPanel"><header class="decision-heading"><p class="eyebrow">320 ／ HEALTH & RUNNING <span>公開・閲覧用</span></p><div class="decision-title"><h2>${E(d.primaryAction)}</h2><div class="priority"><span>?</span>${E(d.priority)}</div></div><p class="decision-lead">${E(d.reason)}</p><p class="decision-purpose">目標に向けて、観測・判断・実行結果をつなぎます。</p><div class="decision-meta"><span>最新観測 ラン ${E(d.observedThrough.running)} ／ 心拍 ${E(d.observedThrough.rhr)} ／ 体重 ${E(d.observedThrough.weight)}</span><span>見直し予定 ${E(d.nextReviewDate)}${today>d.nextReviewDate?'（結果は未確認）':''}</span><a class="text-link" href="#decisionEvidence">判断の根拠を見る →</a></div></header><section class="visual-data" id="visualData"></section><div class="decision-main"><section><p class="section-kicker">NEXT ACTION</p><h3>次に確認すること。</h3><ol class="action-list">${d.actions.map((a,i)=>`<li><span class="action-number">0${i+1}</span><div>${E(a)}</div></li>`).join('')}</ol><p class="quiet">${E(R.raceDate)} 横浜 ／ ${E(R.longTermYear)}年秋 ${E(R.longTermTime)}。今日の体調、目標との差、完走可能性は未判定です。</p></section><section><p class="section-kicker">REASON</p><h3>この順序にした理由。</h3><p class="reason-copy">${E(d.fact)}</p><div class="change-note"><span>↻</span><div><b>今回の調整</b><p>${E(d.changeSummary)}</p></div></div></section></div><section class="cycle-sheet" aria-label="観測から見直しまで"><article class="cycle-item"><span class="cycle-mark">1</span><p>観測</p><b>保存した実測を確認</b><small>記録日と現在を分ける</small></article><article class="cycle-item"><span class="cycle-mark">2</span><p>判断</p><b>既存の方針を維持</b><small>理由・限界を確認</small></article><article class="cycle-item cycle-pending"><span class="cycle-mark">3</span><p>実行と結果</p><b>${E(d.executionState)}</b><small>未入力を未達としない</small></article><article class="cycle-item cycle-pending"><span class="cycle-mark">4</span><p>見直し</p><b>結果を照合してから</b><small>必要なら次の判断へ</small></article></section><div class="review-condition"><p class="section-kicker">REVIEW WHEN</p><p>${E(d.reviewConditions)}</p></div><section id="decisionFeedback" class="data-context"><h3>実行と結果の扱い。</h3><p>${E(d.resultState)}</p><p>${E(d.feedback)}</p></section><details id="decisionEvidence"><summary>理由・研究の根拠と限界を見る</summary><div class="evidence-body"><p>公開した観測：${E(d.fact)}</p><p>AIの参考整理：${E(d.reason)}</p><p>一般研究：<a href="${E(d.evidence.url)}" target="_blank" rel="noopener noreferrer">${E(d.evidence.title)}</a></p><p>対象：${E(d.evidence.population)}</p><p>限界：${E(d.evidence.limit)}</p><p>医療機関の所見は、下の健診資料に測定日と元の判定を付けて表示します。</p></div></details><details id="decisionHistory"><summary>判断の変更点を見る</summary><ol class="decision-history"><li><span>変更前の確認</span><div><b>${E(d.before)}</b></div></li><li><span>今回の扱い</span><div><b>${E(d.after)}</b><p>${E(d.changeSummary)}</p></div></li></ol><p class="quiet">公開用保存 ${E(saved)}。内部の運用ログや私的な入力履歴は公開していません。</p></details></section></div>`;
const observations=[...g.rhr.map((r,i)=>({id:'bpm-'+i,observedDate:r.date,observed:{bpm:r.value},publicSource:g.sourceLabel,publicSeriesSet:r.sourceGroups,importedAt:g.savedAt})),...g.weight.map((r,i)=>({id:'kg-'+i,observedDate:r.date,observed:{kg:r.value},publicSource:g.sourceLabel,publicSeriesSet:r.sourceGroups,importedAt:g.savedAt}))];
window.HealthCharts.mount(document.getElementById('visualData'),observations,today,d.primaryAction,{weekly:g.weekly,sourceLabel:g.sourceLabel,runningThrough:d.observedThrough.running});
const archive=document.createElement('details');archive.className='source-archive';archive.id='sourceArchive';archive.innerHTML='<summary>既存計画・健診・肌の測定資料を見る</summary>';
const first=document.getElementById('r-running');first.before(archive);['r-running','r-checkup','r-skin'].forEach(id=>archive.appendChild(document.getElementById(id)));
document.querySelectorAll('.side__nav a').forEach(a=>a.addEventListener('click',()=>{const id=a.getAttribute('href');if(id==='#r-checkup')archive.open=true;const target=document.querySelector(id);if(target?.tagName==='DETAILS')target.open=true;}));
document.getElementById('freshness').textContent='公開用保存 '+saved+'。最新観測はラン '+d.observedThrough.running+'、安静時心拍 '+d.observedThrough.rhr+'、体重 '+d.observedThrough.weight+'。以後の空白は未観測です。';
})();
